[project]
name = "my-stabilizer-project"
version = "0.1.0"
dependencies = [
    "numpy>=1.20",
    "click",
    "tqdm",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0",
    "hypothesis>=6.0",
]

[project.scripts]
stabcode = "stabilizer.cli:main" 